### PR TITLE
Add git & g++ package (needed for gems from git repos)

### PR DESCRIPTION
**Pull request by QueerCodingGirl**
Without git installed i cannot use gems from git repos.
Bundler gives me this message "You need to install git to be able to use gems from git repositories."

### CODE REVIEW

**Comment by QueerCodingGirl** [comment]
Added the g++ package as well for compiling of native gems

**Comment by sirech** [comment]
cool, thanks for the contribution!

**Comment by QueerCodingGirl** [comment]
@sirech Sadly, the build failed and i do not have a circleci account to see why and fix it. Could you have a look, please?

**Comment by sirech** [comment]
yeah I got a bunch of build failures because in the meantime `docker-compose` has gotten some dependencies that failed the build. I ended up having to base it off `docker:dind` instead of `docker:edge-dind`, which is probably a good idea regardless. The build should be fixed, can you check if it works now?

**Comment by QueerCodingGirl** [comment]
@sirech works just fine now. Thank you very much for creating and maintaining this!

**Pull request merged**
